### PR TITLE
Merge Private Dashboards into Staging

### PR DESCRIPTION
**Pull request by greenstick**

### CODE REVIEW

**Comment by greenstick** [comment]
Working on fixing these checks.

**Comment by greenstick** [comment]
Note: Seems the testing is initially tripping up on email validation – looks like this may be solved by PR #34.

**Comment by greenstick** [comment]
Not sure why deploy is failing here – build is working, deployment is returning a 404.

**Review by megasanjay — APPROVED** [review]

**Comment by greenstick** [comment]
Not ready to merge yet – still requires updates to dashboard API to bring it inline with design of other API endpoints. Will complete merge once that update is in and all checks are passing.

**Pull request merged**
