### PR TITLE
feat: DOI reserved for version table

### PR DESCRIPTION
**Pull request by megasanjay**
@Aydawka Recheck. Broke on merge

### CODE REVIEW

**Comment by Aydawka** [comment]
broke? is there any error occurs on deployment?

**Comment by megasanjay** [comment]
All datasets started showing 500 errors

**Comment by Aydawka** [comment]
@megasanjay  "reset the db -> checkout staging branch -> create the db ( stamp head here) -> add one study (also add an invite here if possible) -> switch to your branch -> run migration (upgrade head) here -> verify data is good and migration succeds"

This workflow has been tested and work.

**Comment by megasanjay** [comment]
Migration still fails on my side

**Comment by Aydawka** [comment]
@megasanjay errors were fixed and pushed

**Comment by megasanjay** [comment]
Can confirm migrations work

**Pull request merged**
